Добавление эндпоинта для запросов вещей от пользователей
spankyntosh/java-shareit pull request #3
Opened 2023-05-17 20:57 UTC by spankyntosh

2023-05-22 12:37 UTC, zgreen3 requested changes
Привет. 

Проверил проект, в целом он соответствует ТЗ и видно, что хорошо проработан, отлично! 
После правки кода на основе комментариев и (или) принятия их к сведению ("Надо исправить" и "Можно лучше"), присылай работу на завершение проверки.

Спасибо.

2023-05-22 12:37 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>          log.info(String.format("Пришёл запрос на подтверждение бронирования %d от пользователя %d", bookingId, userId));
Можно лучше:
В логировании запросов полезно использовать т.н. placeholder "{}" с параметрами из запроса, т.е., например, `log.info("POST request to add an item request with userId: {}", userId);` без необходимости дополнительно использовать String.format(...) внутри метода для логирования.

2023-05-22 12:37 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        log.info(String.format("Пришёл запрос на вещь от пользователя %d", userId));
Можно лучше:

Здесь имеет смысл также залогировать значение параметра itemRequestDTO, т.к. пользователь может запросить множество вещей и в логах без доп. логирования itemRequestDTO будет не ясно, в какой момент, какая вешь обрабатывалась.

2023-05-22 12:37 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        User user = userRepository.findById(userId)
Надо исправить:

В ТЗ указано, что "Запросы должны возвращаться в отсортированном порядке от более новых к более старым".

Нужно добавить эту сортировку на уровне репозитория (подсказка: для таких случаев подходит наследование пользовательского интерфейса репозитория от JpaRepository<...> с методом вроде такого, `List<ItemRequest> findByUser_Id(Long id, Sort sort);` - указал объявление метода как пример, без привязки имён к коду твоего проекта).

2023-05-22 12:37 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        return modelToItemRequestResponseDTOs(requestRepository.findAllExceptRequester(userId, pageRequest));
Надо исправить:

В ТЗ указано, что "Запросы должны возвращаться в отсортированном порядке от более новых к более старым".

Поэтому нужно возвращать отсортированный список. Если используешь JPQL, то можно указать стандартный ORDER BY в этом выражении.

2023-05-22 12:37 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +                                                                                 @RequestParam(required = false, defaultValue = "0") Integer from,
Можно лучше:
Сюда можно добавить аннотацию для валидации поля from `@PositiveOrZero` (https://javaee.github.io/javaee-spec/javadocs/javax/validation/constraints/PositiveOrZero.html), а для следующего параметра - `@Positive` (https://javaee.github.io/javaee-spec/javadocs/javax/validation/constraints/Positive.html). 

Кстати, набор самых употребимых из таких аннотаций см., например, здесь, https://www.logicbig.com/tutorials/java-ee-tutorial/bean-validation/predefined_constraints.html

2023-05-22 12:37 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Integer requestId;
Можно по-другому:

Хотя просто добавить новое поле requestId в этот класс, ItemDto, в соответствие с ТЗ вполне допустимо, можно также указать над классом аннотацию `@JsonInclude(JsonInclude.Include.NON_NULL)`, чтобы уже на данном уровне учесть момент из ТЗ о том, "что должна сохраниться возможность добавить вещь и БЕЗ указания requestId".

2023-05-22 12:37 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    Collection<Item> findAllByOwnerId(Integer ownerId, PageRequest pageRequest);
Отлично:

Вижу (и по этой реализации, и по другим, в т.ч. на уровне контроллеров и кастомных классов для пагинации для item, request, booking), что ты основательно разобрался в теме пагинации и использования её в JpaRepository (с Pageable параметрами), замечательно! Это полезная тема в любых бэкенд-проектах.

2023-05-22 12:37 UTC, zgreen3 commented on src/test/java/ru/practicum/shareit/item/ItemControllerTests.java
> +        verify(itemService).createItem(any(ItemDto.class), anyInt());
Отлично:

Вижу, что в полном соответствии с ТЗ реализованы тесты для REST-эндпоинтов приложения с использованием MockMVC, 
а также, что ты разобрался с работой с моками в Mockito, включая verify-метод, молодец!

Отмечу лишь, что иногда, хотя редко, в легаси-проектах где много технического долга, может пригодиться использование т.н. spy, 
https://www.baeldung.com/mockito-spy (хотя обычно это признак необходимости рефакторинга тестируемого класса), для spy также может пригодиться синтаксис do-return, вместо when-then, https://stackoverflow.com/a/29394497.
Также может пригодиться для тестирования работы методов, когда надо "замокать" выбрасывание исключений, thenThrow(...) синтаксис, https://www.baeldung.com/mockito-exceptions .

2023-05-22 12:37 UTC, zgreen3 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTests.java
> +@WebMvcTest(controllers = BookingController.class)
Отлично:

Вижу, что ты разобрался с тестовыми слайсами, прекрасно! Это всегда полезно использовать для сокращения времени запуска тестов в приложении.

2023-05-22 12:37 UTC, zgreen3 commented on src/test/java/ru/practicum/shareit/booking/BookingServiceIntegrationTests.java
> +@Sql(value = "/testSchema.sql")
Отлично:

Вижу, что ты также разобрался с не самой простой, но важной для полноценного тестирования приложения темой интергационных тестов!

2023-05-22 12:37 UTC, zgreen3 commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTests.java
> +@DataJpaTest
Отлично:

Вижу, что ты также разобрался с DataJpaTest-ами, замечательно!

Кстати, советую в тестовых методах при длинных инициализациях (в данном классе всё нормально, инициализации весьма краткие, это просто примечание для информации)) до вызова тестируемого метода писать в тестовом-методе комментарий "//given", над самим тестируемым методом - "//when", а перед группой ассёртов - "//then" (https://en.wikipedia.org/wiki/Given-When-Then#:~:text=Given-When-Then%20(GWT,words%20given%2C%20when%20and%20then. , https://martinfowler.com/bliki/GivenWhenThen.html), такой подход поможет быстро визуально выделять нужные части длинного тестового метода, а если на проекте будет потом использоваться Cucumber или подобный BDD-фреймворк, то его применение будет привычнее команде, привыкшей так структурировать юнит-тесты.

2023-05-22 12:37 UTC, zgreen3 commented on src/test/java/ru/practicum/shareit/booking/BookingDtoJsonTest.java
> +@JsonTest
Отлично:

Вижу, что ты также освоил тему работы с аннотацией "@JsonTest", так держать!

В любом случае (особенно, если что-то в этой теме осталось "за кадром"), имеет смысл дополнительно ознакомиться с возможностями применения этой аннотации в Spring Boot-проектах,
документации здесь не так много, но можно кое-что почерпнуть дополнительно из примеров реализации, 
см., например, краткое описание (с примером использования) этой аннотации, на англ. яз., тут: https://www.arhohuttunen.com/spring-boot-jsontest/

2023-05-23 15:47 UTC, spankyntosh commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        return modelToItemRequestResponseDTOs(requestRepository.findAllExceptRequester(userId, pageRequest));
Исправил

2023-05-23 15:47 UTC, spankyntosh commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        User user = userRepository.findById(userId)
Исправил

2023-05-23 15:51 UTC, spankyntosh commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Integer requestId;
Поправил

2023-05-23 15:53 UTC, spankyntosh commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +                                                                                 @RequestParam(required = false, defaultValue = "0") Integer from,
Сделал

2023-05-23 15:58 UTC, spankyntosh commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        log.info(String.format("Пришёл запрос на вещь от пользователя %d", userId));
Переделал

2023-05-23 15:58 UTC, spankyntosh commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>          log.info(String.format("Пришёл запрос на подтверждение бронирования %d от пользователя %d", bookingId, userId));
Переделал

2023-05-23 18:21 UTC, zgreen3 approved these changes
Привет, вижу, что ты учёл все важные комментарии, отлично!
Принимаю проект в текущем виде, встретимся на проверке следующих проектов.
Хорошего дня и успехов в освоении важной (и вполне посильной)) темы про докер-контейнеры!

2023-05-24 07:25 UTC, merged